- name: Install dbForge
  win_package:
    path: "{{tools_dbforge_download}}"
    product_id: dbForge
    arguments:
    - /silent

- name: delete default shortcut
  win_shortcut:
    dest: "{{item}}"
    state: absent
  with_items:
    - C:\Users\Administrator\Desktop\dbForge Studio Express for MySQL.lnk
    - C:\Users\websoft9\Desktop\dbForge Studio Express for MySQL.lnk

- name: Create dbForge shortcut to public Desktop
  win_shortcut:
    src: C:\Program Files\Devart\dbForge Studio Express for MySQL\dbforgemysql.exe
    dest: C:\Users\Public\Desktop\dbforgemysql.lnk
    directory: C:\Program Files\Devart\dbForge Studio Express for MySQL\